### PR TITLE
add g0vcloud to footer and fix startcommunity links

### PR DESCRIPTION
**Pull request by djahnie**
Sorry for mixing the footer thing with fixing links...

What do you think of the cloud in the footer? Shall we do it? Stefan asked for it maaaany times and it could be temporarily, right? Still, Doug says it looks strange. Me personally I don't have a strong opinion either way...

### CODE REVIEW

**Comment by stefan-fstaiwan** [comment]
My idea would be to use the logo with the text and also have the link work to their website? Even though I remember we didn't like the "Powered by"
I think just the cloud looks a bit strange and meaningless...
I can understand the resistance against it, but I think it would be fine to put it there for a while, maybe at least as long as we get the grant, ideally one year

**Comment by djahnie** [comment]
I wouldn't add the 'powered by', simply because I think it's too hard to read in this small size. And also because I don't like it... 😛 
But I'm up for adding the link.

**Comment by stefan-fstaiwan** [comment]
g0v

How about this as a link?

**Comment by djahnie** [comment]
Hm dunno, now it's tiny on destop and pretty big in mobile view. Also I didn't make the background transparent, because stuff like that always takes me ages... 😅 
Will make it clickable now.

**Comment by djahnie** [comment]
Okay, clickable it is.
Dunno if I'm too happy with how it looks now though. The size is fine imho, but in desktop view the image is not aligned with the other elements of the footer. I'm not motivated to figure out how to sustainably fix that now though... (Only hackily adding padding in the bottom just feels _wrong_...)

So, what do ther people think?

**Pull request merged**
